# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b404785314044f367d0caa05dd6e83313429454cb4754e26afebdbbb1ee195b796457c976d612bbb17ef66e791830169f04986e20fd395431ddb0554031297

test:
  secret_key_base: 62255f8af06c26b65060f2369bed0d6e6d5e6be059f8604099bc29cea994ada6882ef781550af7439b0fb6695d10b0554e64637d651e177283328c6d85201b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
